name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel ts
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Python Syntax Checker
              uses: EsmoMU/my-first-custom-action@main
